repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  # Checks for a common error of placing code before the docstring
  - id: check-docstring-first
  # Check for files that contain merge conflict strings
  - id: check-merge-conflict
  # Checks that scripts with shebangs are executable
  - id: check-shebang-scripts-are-executable
  # Checks for the existence of AWS secrets that you have set up with the AWS CLI
  - id: detect-aws-credentials
  # Checks for the existence of private keys
  - id: detect-private-key
  # Makes sure files end in a newline and only a newline
  - id: end-of-file-fixer
  # Replaces or checks mixed line ending
  - id: mixed-line-ending
    args: [--fix=lf]
  # Verifies that test files are named correctly
  - id: name-tests-test
    args: [--pytest-test-first]
  # Trims trailing whitespace
  - id: trailing-whitespace
- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.35.0
  hooks:
    # Run `pre-commit install --hook-type commit-msg` to set up the commitizen pre-commit hook
    - id: commitizen
      stages: [commit-msg]
